### ISSUE TITLE
User story latest countouring/webinars

### ISSUE THREAD

**Issue by ColindeGroot** [ColindeGroot/fix-the-flow-interactive-website#3]
Als gebruiker wil ik een popup die informatie weergeeft over de meest recente webinar zodat ik snel alle belangrijke info te zien kan krijgen zonder extra te moeten navigeren

**Comment by ColindeGroot** [comment]
wireflow

![20241202_115858.jpg](https://github.com/user-attachments/assets/e1547d27-064b-4a14-821d-6b5d670bfede)

![20241202_115856.jpg](https://github.com/user-attachments/assets/64fab142-a598-49d5-b2d9-332216d6ae0e)

**Comment by ColindeGroot** [comment]
Breakdown![20241202_120722.jpg](https://github.com/user-attachments/assets/d5be1160-3ef2-4412-ae61-0898ec2c9c40)

![20241202_120716.jpg](https://github.com/user-attachments/assets/80579b99-dcc9-4e4d-a857-1ca95ba6fcda)

**Comment by TomDeeterink1** [comment]
**User story**

User story is nog niet helemaal lekker, let op je zinsopbouw. Idee is daarintegen wel duidelijk! 

**Wireflow**

Ik vindt je wireflow best netjes getekend!  Het is ook uitgebreid genoeg met verschillende states. Ook heb je een goede simpele breakdown gemaakt voor de js events.

**User interactie**

Duidelijke interactie! Creatieve manier om meer informatie te laten zien!

Je bent goed op weg!
